# Generated by Django 4.0.1 on 2022-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='tel',
            field=models.CharField(default=375255435091, max_length=20),
            preserve_default=False,
        ),
    ]
